import { z } from 'zod';
export declare const WhatsAppMessageSchema: any;
export declare const WhatsAppValueSchema: any;
export declare const WhatsAppChangeSchema: any;
export declare const WhatsAppEntrySchema: any;
export declare const WhatsAppWebhookSchema: any;
export type WhatsAppWebhook = z.infer<typeof WhatsAppWebhookSchema>;
export type WhatsAppMessage = z.infer<typeof WhatsAppMessageSchema>;
export declare const JobDataSchema: any;
export type JobData = z.infer<typeof JobDataSchema>;
export declare const ConfigSchema: any;
export type Config = z.infer<typeof ConfigSchema>;
