[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm run start:api"
restartPolicyType = "ON_FAILURE"

[[services]]
name = "api"
startCommand = "npm run start:api"

[[services]]
name = "worker"
startCommand = "npm run start:worker"
