[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "ls -R apps && npm run start:api"
restartPolicyType = "ON_FAILURE"

[[services]]
name = "api"
startCommand = "ls -R apps && npm run start:api"

[[services]]
name = "worker"
startCommand = "ls -R apps && npm run start:worker"
